### ISSUE TITLE
Jadwal Khatib Shalat Jumat dan Shalat Ied

### ISSUE THREAD

**Issue by donisaputrakw** [masjidwatch/masjidwatch#7]
Diharapkan masyarakat bisa mengetahui jadwal khatib di seluruh masjid terdekat dan dapat membantu khatib dalam mengetahui jadwal khutbah di mesjid mana.

**Comment by donisaputra00** [comment]
Difitur ini juga diharapkan memudahkan khutbah yang disampaikan bukan hanya untuk cowok, jadi cewek yg di rumah bisa mengetahui khutbah tersebut
